export const EMPLOYEES = [
  { id: 1,  name: 'Alice Chen',       department: 'Engineering', salary: 95000,  status: 'Active'   },
  { id: 2,  name: 'Bob Martinez',     department: 'Marketing',   salary: 72000,  status: 'Active'   },
  { id: 3,  name: 'Carol White',      department: 'Engineering', salary: 88000,  status: 'Inactive' },
  { id: 4,  name: 'David Kim',        department: 'HR',          salary: 65000,  status: 'Active'   },
  { id: 5,  name: 'Eva Rodriguez',    department: 'Engineering', salary: 102000, status: 'Active'   },
  { id: 6,  name: 'Frank Lee',        department: 'Finance',     salary: 78000,  status: 'Active'   },
  { id: 7,  name: 'Grace Thompson',   department: 'Marketing',   salary: 69000,  status: 'Inactive' },
  { id: 8,  name: 'Henry Wilson',     department: 'Finance',     salary: 85000,  status: 'Active'   },
  { id: 9,  name: 'Iris Patel',       department: 'HR',          salary: 67000,  status: 'Active'   },
  { id: 10, name: 'James Brown',      department: 'Engineering', salary: 91000,  status: 'Active'   },
  { id: 11, name: 'Karen Davis',      department: 'Marketing',   salary: 74000,  status: 'Active'   },
  { id: 12, name: 'Leo Garcia',       department: 'Finance',     salary: 80000,  status: 'Inactive' },
  { id: 13, name: 'Mia Johnson',      department: 'HR',          salary: 63000,  status: 'Active'   },
  { id: 14, name: 'Nathan Moore',     department: 'Engineering', salary: 98000,  status: 'Active'   },
  { id: 15, name: 'Olivia Taylor',    department: 'Marketing',   salary: 71000,  status: 'Active'   },
  { id: 16, name: 'Paul Anderson',    department: 'Finance',     salary: 82000,  status: 'Active'   },
  { id: 17, name: 'Quinn Harris',     department: 'HR',          salary: 66000,  status: 'Inactive' },
  { id: 18, name: 'Rachel Jackson',   department: 'Engineering', salary: 94000,  status: 'Active'   },
  { id: 19, name: 'Sam Thomas',       department: 'Marketing',   salary: 76000,  status: 'Active'   },
  { id: 20, name: 'Zara Williams',    department: 'Finance',     salary: 79000,  status: 'Active'   },
]
